symbols = {
    "FBAL PFR SOJ", "FBAL PFR MIL", "FUBE SAN SOJ", "FNMT SAN SOJ",
    "FRON SAN SOJ", "FRON SAN MIL", "FVRE SAN SOJ", "FURU SLU SOJ",
    "FURU SLU MIL", "FJAT SAN SOJ", "FJAT PGU SOJ", "FCRI SAN SOJ",
    "FRVE SAN SOJ", "FRVE SAN MIL", "FQUE SLU SOJ", "FQUE BAR SOJ",
    "FSOR SAN SOJ", "FSOR PGU SOJ", "FSOR SAN MIL", "FSOR PGU MIL"
}

